# Generated by Django 4.2.6 on 2023-12-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vod',
            name='text',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
