# Generated by Django 4.2.6 on 2023-11-16 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vod",
            name="runningtime",
        ),
    ]
