# Generated by Django 4.2.6 on 2023-11-21 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vod',
            name='backgroundimgpath',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vod',
            name='name_no_space',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
