# Generated by Django 4.2.6 on 2023-11-20 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vod",
            name="name_no_space",
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
