# Generated by Django 4.2.6 on 2023-11-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0002_remove_vod_runningtime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vod",
            name="description",
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="vod",
            name="imgpath",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
