# Generated by Django 4.2.6 on 2023-11-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0002_alter_vod_actors"),
    ]

    operations = [
        migrations.AddField(
            model_name="vod",
            name="count",
            field=models.IntegerField(null=True),
        ),
    ]
