# Generated by Django 4.2.6 on 2023-12-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_alter_vod_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vod',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vod',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
