# Generated by Django 4.2.6 on 2023-12-01 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0003_vod_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="vod",
            name="choseong",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
