# Generated by Django 4.2.6 on 2023-12-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_vod_choseong'),
    ]

    operations = [
        migrations.AddField(
            model_name='vod',
            name='actorsimage',
            field=models.JSONField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vod',
            name='actors',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
