# Generated by Django 4.2.6 on 2023-11-30 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contents', '0003_vod_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainRecommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stbnum', models.IntegerField()),
                ('method', models.IntegerField()),
                ('rec1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents1', to='contents.vod')),
                ('rec10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='contents.vod')),
                ('rec2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents2', to='contents.vod')),
                ('rec3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents3', to='contents.vod')),
                ('rec4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents4', to='contents.vod')),
                ('rec5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents5', to='contents.vod')),
                ('rec6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents6', to='contents.vod')),
                ('rec7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents7', to='contents.vod')),
                ('rec8', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents8', to='contents.vod')),
                ('rec9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents9', to='contents.vod')),
            ],
        ),
    ]
