# Generated by Django 4.2.6 on 2023-12-15 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
        ('recommends', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeRecommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yesterday', models.BooleanField()),
                ('today', models.BooleanField()),
                ('tomorrow', models.BooleanField()),
                ('time', models.IntegerField()),
                ('method', models.IntegerField()),
                ('rec1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cont1', to='contents.vod')),
                ('rec10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cont10', to='contents.vod')),
                ('rec2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cont2', to='contents.vod')),
                ('rec3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cont3', to='contents.vod')),
                ('rec4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cont4', to='contents.vod')),
                ('rec5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cont5', to='contents.vod')),
                ('rec6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cont6', to='contents.vod')),
                ('rec7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cont7', to='contents.vod')),
                ('rec8', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cont8', to='contents.vod')),
                ('rec9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cont9', to='contents.vod')),
            ],
        ),
    ]
