# Generated by Django 4.2.6 on 2023-12-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommends', '0002_timerecommend'),
    ]

    operations = [
        migrations.CreateModel(
            name='vod_score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substr', models.IntegerField()),
                ('vod_id', models.IntegerField()),
                ('score', models.FloatField()),
            ],
        ),
    ]
