# Generated by Django 4.2.6 on 2023-12-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_social',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='prefer_contents',
            field=models.JSONField(null=True),
        ),
    ]
