# Generated by Django 4.2.6 on 2023-11-30 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='stbnumber',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
