# Generated by Django 4.2.6 on 2023-12-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_vod_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vod',
            name='text',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
